### ISSUE TITLE
请教下博文中的软件调用流程图所使用的绘图工具

### ISSUE THREAD

**Issue by weycen** [schspa/schspa.github.io#4]
你好，请教下博文中的如下两幅图所使用的绘图工具是什么？

<https://schspa.github.io/2020/07/10/assets/suspend-to-ram.png>
<https://schspa.github.io/2020/07/10/assets/atf-suspend-resume.png>

谢谢！

**Comment by schspa** [comment]
> 
https://schspa.github.io/2020/07/10/assets/suspend-to-ram.png
这个是用的[draw.io](https://app.diagrams.net/)
https://schspa.github.io/2020/07/10/assets/atf-suspend-resume.png
这个是用的[plantuml](https://plantuml.com/zh/)

**Comment by weycen** [comment]
收到，万分感谢！
